### ISSUE TITLE
Not working as expected when commenting multiple changed hunks in file

### ISSUE THREAD

**Issue by ahmetrehaseker** [owenrumney/go-github-pr-commenter#14]
**Describe the bug**
If there is a one part is changed in file and you try to add a comment there it works but if there is a multiple changes hunks and you try to add a comment in second hunk library says it is not in pr.

**To Reproduce**
1. Change first line and last line of a file and create a pr with that change
2. Try to add a comment on last line
3. Get the error CommentNotValidError 

**Expected behavior**
Library should create the comment on the last line

**Comment by rym-dd** [comment]
Hi @owenrumney 

Do you think you can take a look to this issue?

Thanks.

**Comment by owenrumney** [comment]
I'm away till Sunday but have made a note to take a look then. 

I think I understand the scenario so will try and reproduce then fix

**Comment by ahmetrehaseker** [comment]
I have a small fix for this but unable to test it, I will create the pr today

**Comment by kobylianskii** [comment]
Hey @owenrumney! Do you think we can help somehow with this? There's an [issue](https://github.com/aquasecurity/tfsec-pr-commenter-action/issues/90) and I think many people are waiting for the fix.

**Comment by GregUK** [comment]
I have been trying to make use of the feature and I have hit this issue when attempting to use the tf-sec-commentor action

**Comment by owenrumney** [comment]
I'll take a look at the fix that was PR'd shortly. 

It's my understanding that aqua are not long support tfsec or any of the associated tooling like the PR commenter. I think even when this is resolved here, it won't make it's way to tfsec commenter - Just fyi

**Comment by owenrumney** [comment]
released as v0.1.3 - good luck with getting it into tfsec

**Comment by GregUK** [comment]
Thanks @owenrumney, appreciate it.

**Comment by kobylianskii** [comment]
@owenrumney thanks a lot! 

> I think even when this is resolved here, it won't make it's way to tfsec commenter

But you're the main contributor there or am I wrong? 😑

**Comment by owenrumney** [comment]
> @owenrumney thanks a lot!
> 
> > I think even when this is resolved here, it won't make it's way to tfsec commenter
> 
> But you're the main contributor there or am I wrong? 😑

I was, till I left Aqua and lost my access
